name: Codacy Coverage

on:
  push:
    branches:
      - main  # Modify this branch as needed
  pull_request:
    branches:
      - main  # Modify this branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler
        run: gem install bundler

      - name: Install project dependencies
        run: bundle install

      - name: Run tests with coverage
        run: bundle exec rspec --require ./spec/spec_helper.rb

      - name: Upload coverage report to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage/.resultset.json

